services:
  # === ИНФРАСТРУКТУРА ===
  kafka:
    # ПЕРЕХОДИМ НА ОФИЦИАЛЬНЫЙ ОБРАЗ
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Настройки для Apache Kafka (KRaft mode)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      # Самое важное: рекламируем себя как "kafka" для внутренней сети
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      
      # Настройки для работы в одиночном режиме (без репликации)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      # Путь внутри контейнера у Apache другой: /var/lib/kafka/data
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      # Путь к скриптам тоже другой: /opt/kafka/bin/...
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8.5
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
    depends_on:
      - postgres

  # === НАШИ МИКРОСЕРВИСЫ ===
  
  collector:
    build:
      context: .
      dockerfile: src/collector/Dockerfile
    container_name: app-collector
    # volumes:
    #   - ./src:/app/src
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      - KAFKA_BROKER=kafka:9092
      - DB_HOST=postgres
      - PYTHONPATH=/app/src
  processor:
    build:
      context: .
      dockerfile: src/processor/Dockerfile
      args:
        APT_MIRROR: mirror.yandex.ru
    container_name: app-processor
    # volumes:
    #   - ./src:/app/src
    depends_on:
      kafka:
        condition: service_healthy
    env_file: .env
    environment:
      - KAFKA_BROKER=kafka:9092
      - API_DELAY=${API_DELAY}
      - DB_HOST=postgres
      - PYTHONPATH=/app/src
  publisher:
    build:
      context: .
      dockerfile: src/publisher/Dockerfile
    container_name: app-publisher
    # volumes:
    #   - ./src:/app/src
    depends_on:
      kafka:
        condition: service_healthy
    env_file: .env
    environment:
      - KAFKA_BROKER=kafka:9092
      - PYTHONPATH=/app/src

volumes:
  kafka_data:
  postgres_data: